#
# Copyright (c) 2022 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/cryptecs/cryptecs.github.io.
#
# SPDX-License-Identifier: CC-BY-4.0
#
MD013:
  code_blocks : false
  tables : false
MD033: false
MD037: false
MD046: false
